In [3]:
import numpy as np
import pandas as pd

# Load the data
anagrams_data = pd.read_csv('Sampledata/anagrams.csv')
anagrams_data.sort_values(by='num1')

    subidr    attnr  num1  num2  num3
0        1  divided     2   4.0     7
8        9  divided     2   3.0     7
1        2  divided     3   4.0     5
2        3  divided     3   5.0     6
4        5  divided     4   5.0     8
3        4  divided     5   7.0     5
5        6  divided     5   5.0     6
6        7  divided     5   4.5     6
7        8  divided     5   7.0     8
18      19  focused     5   6.0     6
15      16  focused     6   8.0     7
12      13  focused     6   5.0     9
9       10  divided     6   5.0     6
10      11  focused     6   5.0     6
19      20  focused     6   6.0     5
16      17  focused     7   7.0     6
17      18  focused     7   8.0     6
13      14  focused     8   8.0     7
14      15  focused     8   8.0     7
11      12  focused     8   9.0     8