# Thu thap du lieu Crypto

In [2]:
import sys
sys.path.append('../Common/')

import CommonBinance

In [5]:
# Ví dụ: Gọi hàm để lấy dữ liệu từ '2023-01-01' đến '2023-12-31'
symbol = "EURUSDT"
from_date = "2020-01-01"
to_date = "2023-12-31"
timeframe = '1d'
data = CommonBinance.CommonBinance.loaddataBinance_FromTo_Split(symbol, from_date, to_date, timeframe)

In [6]:
data

      Datetime    Open    High     Low   Close       Volume
0   2020-01-03  1.1154  1.1200  1.1126  1.1157     59792.54
1   2020-01-04  1.1179  1.1192  1.1153  1.1160     41718.81
2   2020-01-05  1.1187  1.1188  1.1154  1.1162     59930.02
3   2020-01-06  1.1162  4.9500  1.1155  1.1179    119105.93
4   2020-01-07  1.1211  1.1248  1.1131  1.1174    383817.69
..         ...     ...     ...     ...     ...          ...
479 2024-01-21  1.0883  1.0885  1.0872  1.0884   7209679.50
480 2024-01-22  1.0884  1.0905  1.0875  1.0878  22358994.60
481 2024-01-23  1.0878  1.0914  1.0822  1.0847  26537729.80
482 2024-01-24  1.0847  1.0924  1.0843  1.0880  25450829.00
483 2024-01-25  1.0880  1.0897  1.0870  1.0874  18986332.50

[1484 rows x 6 columns]

In [7]:
data['SMA'] = 'Cai gi do'

In [8]:
data

      Datetime    Open    High     Low   Close       Volume        SMA
0   2020-01-03  1.1154  1.1200  1.1126  1.1157     59792.54  Cai gi do
1   2020-01-04  1.1179  1.1192  1.1153  1.1160     41718.81  Cai gi do
2   2020-01-05  1.1187  1.1188  1.1154  1.1162     59930.02  Cai gi do
3   2020-01-06  1.1162  4.9500  1.1155  1.1179    119105.93  Cai gi do
4   2020-01-07  1.1211  1.1248  1.1131  1.1174    383817.69  Cai gi do
..         ...     ...     ...     ...     ...          ...        ...
479 2024-01-21  1.0883  1.0885  1.0872  1.0884   7209679.50  Cai gi do
480 2024-01-22  1.0884  1.0905  1.0875  1.0878  22358994.60  Cai gi do
481 2024-01-23  1.0878  1.0914  1.0822  1.0847  26537729.80  Cai gi do
482 2024-01-24  1.0847  1.0924  1.0843  1.0880  25450829.00  Cai gi do
483 2024-01-25  1.0880  1.0897  1.0870  1.0874  18986332.50  Cai gi do

[1484 rows x 7 columns]

# Chen vao DWH: Không có user và password

In [9]:
import urllib.parse
import sqlalchemy

driver = 'ODBC Driver 17 for SQL Server'
server = '.'  # hoặc tên server của bạn
database = 'DWH'  # thay đổi tên database nếu cần

# Tạo chuỗi kết nối
params = urllib.parse.quote_plus(f'DRIVER={driver};SERVER={server};DATABASE={database};Trusted_Connection=yes')
connection_string = f"mssql+pyodbc:///?odbc_connect={params}"

# Tạo engine kết nối
engine = sqlalchemy.create_engine(connection_string)

# Lưu DataFrame vào SQL Server
table_name = 'Crypto_Data'
data.to_sql(table_name, con=engine, if_exists='append', index=False)

288

# Chen vao DWH: Có user và password

In [4]:
# import urllib.parse
# import sqlalchemy

# driver = 'ODBC Driver 17 for SQL Server'
# server = '.'  # hoặc tên server của bạn
# database = 'DWH'  # thay đổi tên database nếu cần
# username = 'sa'  # tên người dùng của bạn
# password = '1'  # mật khẩu của bạn

# # Tạo chuỗi kết nối
# params = urllib.parse.quote_plus(f'DRIVER={driver};SERVER={server};DATABASE={database};UID={username};PWD={password}')
# connection_string = f"mssql+pyodbc:///?odbc_connect={params}"

# # Tạo engine kết nối
# engine = sqlalchemy.create_engine(connection_string)

# # Lưu DataFrame vào SQL Server
# table_name = 'ChungKhoan_Data'
# data.to_sql(table_name, con=engine, if_exists='append', index=False)